(setq inhibit-startup-screen t)
(setq-default indent-tabs-mode nil)
(setq-default js-indent-level 2)
(require 'whitespace)
(setq whitespace-style '(face empty tabs lines-tail trailing))
(global-whitespace-mode t)
(setq org-log-done t)
